name: Audio Downloader
description: Download songs, albums, or playlists from Spotify and YouTube as MP3 files
url: https://github.com/rundercaster/playlistdl-ha
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
version: 1.0.3
slug: playlistdl
init: false
startup: services
ports:
  5000/tcp: 5000
host_network: false
map:
  - share:rw
options:
  admin_username: admin
  admin_password: changeme
  audio_download_path: /share/playlistdl
  cleanup_interval: 300
schema:
  admin_username: str
  admin_password: password
  audio_download_path: str
  cleanup_interval: int
