name: Audio Downloader
description: Download songs, albums, or playlists from Spotify and YouTube as MP3 files
url: https://github.com/rundercaster/playlistdl-ha
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
version: 1.0.6
slug: playlistdl
init: false
startup: services
ingress: true
ingress_port: 5000
ports:
  5000/tcp: 5000
host_network: false
map:
  - media:rw
options:
  audio_download_path: /media
  cleanup_interval: 300
schema:
  audio_download_path: str
  cleanup_interval: int
